"use client";

import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import { MessageCircle, Plus, Search, UserRound, X } from "lucide-react";
import { useMemo, useState } from "react";

type Client = { id: string; name: string; phone: string; notes?: string | null; appointments: { startsAt: string; service: { name: string } }[] };
const phone = (value: string) => value.length === 11 ? `(${value.slice(0,2)}) ${value.slice(2,7)}-${value.slice(7)}` : value;

export function ClientsClient({ initialClients }: { initialClients: Client[] }) {
  const [clients, setClients] = useState(initialClients); const [query, setQuery] = useState(""); const [modal, setModal] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => clients.filter((c) => `${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const fd = new FormData(e.currentTarget); const res = await fetch("/api/clients", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(Object.fromEntries(fd)) }); const data = await res.json(); if(!res.ok) return setError(data.error); setClients((c) => [...c, { ...data, appointments: [] }].sort((a,b)=>a.name.localeCompare(b.name))); setModal(false); }
  return <><div className="page-heading"><div><span className="eyebrow">RELACIONAMENTO</span><h1>Clientes</h1><p>{clients.length} pessoas na sua base.</p></div><button className="button primary" onClick={()=>setModal(true)}><Plus size={18}/> Novo cliente</button></div><section className="panel table-panel"><div className="table-tools"><div className="field-search"><Search size={17}/><input placeholder="Buscar por nome ou telefone" value={query} onChange={(e)=>setQuery(e.target.value)}/></div><span>{filtered.length} resultados</span></div><div className="data-table"><div className="table-row table-head"><span>Cliente</span><span>Contato</span><span>Último atendimento</span><span>Observação</span><span/></div>{filtered.map((client)=><div className="table-row" key={client.id}><div className="client-cell"><span className="client-avatar"><UserRound size={16}/></span><strong>{client.name}</strong></div><span>{phone(client.phone)}</span><span>{client.appointments[0] ? `${client.appointments[0].service.name} · ${format(new Date(client.appointments[0].startsAt),"dd MMM",{locale:ptBR})}` : "Ainda não atendido"}</span><span className="truncate">{client.notes || "—"}</span><a className="whatsapp-link" href={`https://wa.me/55${client.phone}`} target="_blank"><MessageCircle size={17}/></a></div>)}</div></section>{modal&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">NOVO CONTATO</span><h2>Adicionar cliente</h2></div><button onClick={()=>setModal(false)}><X/></button></div><form className="form-grid" onSubmit={submit}><label>Nome<input name="name" required placeholder="Nome completo"/></label><label>WhatsApp<input name="phone" required placeholder="(47) 99999-9999"/></label><label className="full">Observações<textarea name="notes" rows={3} placeholder="Preferências ou informações úteis"/></label>{error&&<p className="form-error full">{error}</p>}<div className="modal-actions full"><button type="button" className="button outline" onClick={()=>setModal(false)}>Cancelar</button><button className="button primary">Adicionar cliente</button></div></form></div></div>}</>;
}
